title: <p align="center"> Ajay LAMKHADE </p>
logo: /assets/img/ajax1.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ajay-lamkhade-4410a03a/">LinkedIn</a> |
  <a href="https://github.com/ajaylamkhade">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
